name: Deploy HSWebAppTwo app to Google kubernetes Engine


on: [workflow_dispatch]

env:
  GKE_PROJECT: ${{ secrets.GKE_PROJECT }}
  GKE_CLUSTER: hschan-demo-cluster
  GKE_APP_NAME: hschan-demo-webapp2
  GKE_SERVICE: hschan-service
  GKE_SERVICE_ACCOUNT: hschan-serviceaccount
  GKE_DEPLOYMENT_NAME: hschan-demo-webapp1-deployment
  GKE_REGION: us-central1
  GKE_ZONE: us-central1-c
 # Just a placeholder for the first deployment
  GITHUB_SHA: Test


  
  
jobs:
  Build:
    runs-on: ubuntu-latest

    # Add "id-token" with the intended permissions.
    permissions:
      contents: 'read'
      id-token: 'write'
      
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    #- uses: google-github-actions/setup-gcloud@v0.6.0
    #  with:
    #    service_account_key: ${{ secrets.GKE_SA_KEY }}
    #    project_id: ${{ secrets.GKE_PROJECT }}
    #    export_default_credentials: true 
        
        
    # Configure Workload Identity Federation and generate an access token.
    - id: 'auth'
      name: 'Authenticate to Google Cloud'
      uses: 'google-github-actions/auth@v1'
      with:
        token_format: "access_token"
        create_credentials_file: true
        workload_identity_provider: 'projects/549315440769/locations/global/workloadIdentityPools/github-wif-pool/providers/githubwif'
        service_account: 'hschan-serviceaccount@sincere-actor-374621.iam.gserviceaccount.com'
        

    # Build the Docker image
    - name: Build and Push
      working-directory: HSWebAppTWO
      run: |-  
        docker build \
          --tag "$GKE_REGION-docker.pkg.dev/$GKE_PROJECT/$GKE_PROJECT/$GKE_APP_NAME:$GITHUB_SHA" \
          --build-arg GITHUB_SHA="$GITHUB_SHA" \
          --build-arg GITHUB_REF="$GITHUB_REF" \
          .
        gcloud auth configure-docker $GKE_REGION-docker.pkg.dev --quiet
        docker push "$GKE_REGION-docker.pkg.dev/$GKE_PROJECT/$GKE_PROJECT/$GKE_APP_NAME:$GITHUB_SHA"     

  Deploy:
    runs-on: ubuntu-latest
    environment: prod
    needs: Build

    steps:
    - name: Checkout
      uses: actions/checkout@v3

    # Setup gcloud CLI
    - uses: google-github-actions/setup-gcloud@v0.6.0
      with:
        service_account_key: ${{ secrets.GKE_SA_KEY }}
        project_id: ${{ secrets.GKE_PROJECT }}
        export_default_credentials: true 

    # Get the GKE credentials so we can deploy to the cluster
    - uses: google-github-actions/get-gke-credentials@v0.5.0
      with:
        cluster_name: ${{ env.GKE_CLUSTER }}
        location: ${{ env.GKE_ZONE }}
        credentials: ${{ secrets.GKE_SA_KEY }}

    # Deploy the new Docker image to the GKE cluster
    - name: Deploy
      working-directory: HSWebAppTWO
      run: |-
        envsubst < Service.yml | kubectl apply -f -
        envsubst < Deployment.yml | kubectl apply -f -
